import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar } from './ui'
import { auth } from '@/auth'
import { Providers } from './providers'
import { dbConnect } from '@/lib/mongodb'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({ children }) {
  await dbConnect()
  const session = await auth()

  return (
    <html lang="es">
      <body className={`${inter.className} container`}>
        <Providers>
          <Navbar session={session} />
          <main className="mt-24">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
